spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?currentSchema=${MYSQL_DATABASE}&allowPublicKeyRetrieval=true&useSSL=false
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
  jpa.hibernate.ddl-auto: update

liquibase.default-schema: ${MYSQL_DATABASE}
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
server.port: ${PORT}

aws.s3.endpoint: https://s3-ap-southeast-1.amazonaws.com/