spring:
  datasource:
    url: ${CLEARDB_DATABASE_URL}
    driver-class-name: com.mysql.jdbc.Driver
  jpa.hibernate.ddl-auto: update

liquibase.default-schema: ${MYSQL_DATABASE}
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
server.port: ${PORT}

aws.s3.endpoint: https://s3-ap-southeast-1.amazonaws.com/