// Navigation
export const CHANGE_ROUTE = 'CHANGE_ROUTE'

// Blog
export const GET_POST = 'GET_POST'
export const GET_POST_OK = 'GET_POST_OK'
export const GET_POST_ERROR = 'GET_POST_ERROR'

export const GET_POST_CATEGORY = 'GET_POST_CATEGORY'
export const GET_POST_CATEGORY_OK = 'GET_POST_CATEGORY_OK'
export const GET_POST_CATEGORY_ERROR = 'GET_POST_CATEGORY_ERROR'

export const GET_POST_BY_ID = 'GET_POST_BY_ID'
export const GET_POST_BY_ID_OK = 'GET_POST_BY_ID_OK'
export const GET_POST_BY_ID_ERROR = 'GET_POST_BY_ID_ERROR'

export const ADD_POST = 'ADD_POST'
export const ADD_POST_OK = 'ADD_POST_OK'
export const ADD_POST_ERROR = 'ADD_POST_ERROR'

export const UPLOAD_POST_IMAGE = 'UPLOAD_POST_IMAGE'
export const UPLOAD_POST_IMAGE_OK = 'UPLOAD_POST_IMAGE_OK'
export const UPLOAD_POST_IMAGE_ERROR = 'UPLOAD_POST_IMAGE_ERROR'
